version: "3"
services:

  db:
      image: mysql
      container_name: db_teds_dashboard
      restart: always
      volumes:
        - db-data:/var/lib/mysql
      environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      networks:
        - dev

  phpmyadmin:
      image: phpmyadmin
      container_name: phpmyadmin_teds_dashboard
      restart: always
      depends_on:
        - db
      ports:
        - 8080:80
      environment:
        PMA_HOST: db
      networks:
        - dev

  maildev:
      image: maildev/maildev
      container_name: maildev_teds_dashboard
      command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
      ports:
        - "8081:80"
      restart: always
      networks:
        - dev

  www:
      build: php
      container_name: www_teds_dashboard
      ports:
        - "8082:80"
      volumes:
        - ./php/vhosts:/etc/apache2/sites-enabled
        - ./:/var/www
      restart: always
      networks:
        - dev

networks:
    dev:

volumes:
    db-data:
